### ISSUE TITLE
BUG: Adding reactions or replying giving an error

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4420]
**Describe the bug**
Reply to a message, or add an emoticon reaction - server error:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/ee8f516a-33ae-4d3e-9f3d-cb8274a7c8f4)

**To Reproduce**

1. Go to any conversation, I was using https://alkem.io/challengecentric/collaboration/hiintroduceyourse-3560
2. Add a reaction / reply, get an error. Refreshing the page shows that the data is there - but highly likely the notifications related to it failed. 

**Expected behavior**
Adding a reply / reacting should show up directly and notifications are triggered.

**Comment by valentinyanakiev** [comment]
{"context":"challenges","label":"alkemio-server","level":"error","message":"Unable to find Space with ID: help-oekraine","stack":["\"GraphQLError: Unable to find Space with ID: help-oekraine\\n    at new BaseException (/usr/src/app/dist/common/exceptions/base.exception.js:7:9)\\n    at new EntityNotFoundException (/usr/src/app/dist/common/exceptions/entity.not.found.exception.js:8:9)\\n    at SpaceService.getSpaceOrFail (/usr/src/app/dist/domain/challenge/space/space.service.js:356:19)\\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\\n    at async SpaceResolverQueries.space (/usr/src/app/dist/domain/challenge/space/space.resolver.queries.js:34:16)\""],"timestamp":"2023-07-21T23:16:47.945Z"}
{"context":"challenges","label":"alkemio-server","level":"error","message":"Unable to find Space with ID: help-oekraine","stack":["\"GraphQLError: Unable to find Space with ID: help-oekraine\\n    at new BaseException (/usr/src/app/dist/common/exceptions/base.exception.js:7:9)\\n    at new EntityNotFoundException (/usr/src/app/dist/common/exceptions/entity.not.found.exception.js:8:9)\\n    at SpaceService.getSpaceOrFail (/usr/src/app/dist/domain/challenge/space/space.service.js:356:19)\\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\\n    at async SpaceResolverQueries.space (/usr/src/app/dist/domain/challenge/space/space.resolver.queries.js:34:16)\""],"timestamp":"2023-07-21T23:16:48.540Z"}
{"context":"challenges","label":"alkemio-server","level":"error","message":"Unable to find Space with ID: help-oekraine","stack":["\"GraphQLError: Unable to find Space with ID: help-oekraine\\n    at new BaseException (/usr/src/app/dist/common/exceptions/base.exception.js:7:9)\\n    at new EntityNotFoundException (/usr/src/app/dist/common/exceptions/entity.not.found.exception.js:8:9)\\n    at SpaceService.getSpaceOrFail (/usr/src/app/dist/domain/challenge/space/space.service.js:356:19)\\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\\n    at async SpaceResolverQueries.space (/usr/src/app/dist/domain/challenge/space/space.resolver.queries.js:34:16)\""],"timestamp":"2023-07-21T23:16:48.964Z"}
{"context":"challenges","label":"alkemio-server","level":"error","message":"Unable to find Space with ID: help-oekraine","stack":["\"GraphQLError: Unable to find Space with ID: help-oekraine\\n    at new BaseException (/usr/src/app/dist/common/exceptions/base.exception.js:7:9)\\n    at new EntityNotFoundException (/usr/src/app/dist/common/exceptions/entity.not.found.exception.js:8:9)\\n    at SpaceService.getSpaceOrFail (/usr/src/app/dist/domain/challenge/space/space.service.js:356:19)\\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\\n    at async SpaceResolverQueries.space (/usr/src/app/dist/domain/challenge/space/space.resolver.queries.js:34:16)\""],"timestamp":"2023-07-21T23:16:49.588Z"}
{"context":"challenges","label":"alkemio-server","level":"error","message":"Unable to find Space with ID: partners","stack":["\"GraphQLError: Unable to find Space with ID: partners\\n    at new BaseException (/usr/src/app/dist/common/exceptions/base.exception.js:7:9)\\n    at new EntityNotFoundException (/usr/src/app/dist/common/exceptions/entity.not.found.exception.js:8:9)\\n    at SpaceService.getSpaceOrFail (/usr/src/app/dist/domain/challenge/space/space.service.js:356:19)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\\n    at async SpaceResolverQueries.space (/usr/src/app/dist/domain/challenge/space/space.resolver.queries.js:34:16)\""],"timestamp":"2023-07-22T04:32:57.120Z"}
{"context":"challenges","label":"alkemio-server","level":"error","message":"Unable to find Space with ID: partners","stack":["\"GraphQLError: Unable to find Space with ID: partners\\n    at new BaseException (/usr/src/app/dist/common/exceptions/base.exception.js:7:9)\\n    at new EntityNotFoundException (/usr/src/app/dist/common/exceptions/entity.not.found.exception.js:8:9)\\n    at SpaceService.getSpaceOrFail (/usr/src/app/dist/domain/challenge/space/space.service.js:356:19)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\\n    at async SpaceResolverQueries.space (/usr/src/app/dist/domain/challenge/space/space.resolver.queries.js:34:16)\""],"timestamp":"2023-07-22T04:32:57.583Z"}
{"context":"challenges","label":"alkemio-server","level":"error","message":"Unable to find Space with ID: partners","stack":["\"GraphQLError: Unable to find Space with ID: partners\\n    at new BaseException (/usr/src/app/dist/common/exceptions/base.exception.js:7:9)\\n    at new EntityNotFoundException (/usr/src/app/dist/common/exceptions/entity.not.found.exception.js:8:9)\\n    at SpaceService.getSpaceOrFail (/usr/src/app/dist/domain/challenge/space/space.service.js:356:19)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\\n    at async SpaceResolverQueries.space (/usr/src/app/dist/domain/challenge/space/space.resolver.queries.js:34:16)\""],"timestamp":"2023-07-22T04:32:57.650Z"}
{"context":"challenges","label":"alkemio-server","level":"error","message":"Unable to find Space with ID: partners","stack":["\"GraphQLError: Unable to find Space with ID: partners\\n    at new BaseException (/usr/src/app/dist/common/exceptions/base.exception.js:7:9)\\n    at new EntityNotFoundException (/usr/src/app/dist/common/exceptions/entity.not.found.exception.js:8:9)\\n    at SpaceService.getSpaceOrFail (/usr/src/app/dist/domain/challenge/space/space.service.js:356:19)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\\n    at async SpaceResolverQueries.space (/usr/src/app/dist/domain/challenge/space/space.resolver.queries.js:34:16)\""],"timestamp":"2023-07-22T04:32:57.651Z"}
{"context":"challenges","label":"alkemio-server","level":"error","message":"Unable to find Space with ID: partners","stack":["\"GraphQLError: Unable to find Space with ID: partners\\n    at new BaseException (/usr/src/app/dist/common/exceptions/base.exception.js:7:9)\\n    at new EntityNotFoundException (/usr/src/app/dist/common/exceptions/entity.not.found.exception.js:8:9)\\n    at SpaceService.getSpaceOrFail (/usr/src/app/dist/domain/challenge/space/space.service.js:356:19)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\\n    at async SpaceResolverQueries.space (/usr/src/app/dist/domain/challenge/space/space.resolver.queries.js:34:16)\""],"timestamp":"2023-07-22T04:32:57.771Z"}
{"context":"challenges","label":"alkemio-server","level":"error","message":"Unable to find Space with ID: partners","stack":["\"GraphQLError: Unable to find Space with ID: partners\\n    at new BaseException (/usr/src/app/dist/common/exceptions/base.exception.js:7:9)\\n    at new EntityNotFoundException (/usr/src/app/dist/common/exceptions/entity.not.found.exception.js:8:9)\\n    at SpaceService.getSpaceOrFail (/usr/src/app/dist/domain/challenge/space/space.service.js:356:19)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\\n    at async SpaceResolverQueries.space (/usr/src/app/dist/domain/challenge/space/space.resolver.queries.js:34:16)\""],"timestamp":"2023-07-22T04:32:58.572Z"}
{"context":"challenges","label":"alkemio-server","level":"error","message":"Unable to find Space with ID: partners","stack":["\"GraphQLError: Unable to find Space with ID: partners\\n    at new BaseException (/usr/src/app/dist/common/exceptions/base.exception.js:7:9)\\n    at new EntityNotFoundException (/usr/src/app/dist/common/exceptions/entity.not.found.exception.js:8:9)\\n    at SpaceService.getSpaceOrFail (/usr/src/app/dist/domain/challenge/space/space.service.js:356:19)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\\n    at async SpaceResolverQueries.space (/usr/src/app/dist/domain/challenge/space/space.resolver.queries.js:34:16)\""],"timestamp":"2023-07-22T04:32:58.823Z"}
{"context":"challenges","label":"alkemio-server","level":"error","message":"Unable to find Space with ID: partners","stack":["\"GraphQLError: Unable to find Space with ID: partners\\n    at new BaseException (/usr/src/app/dist/common/exceptions/base.exception.js:7:9)\\n    at new EntityNotFoundException (/usr/src/app/dist/common/exceptions/entity.not.found.exception.js:8:9)\\n    at SpaceService.getSpaceOrFail (/usr/src/app/dist/domain/challenge/space/space.service.js:356:19)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\\n    at async SpaceResolverQueries.space (/usr/src/app/dist/domain/challenge/space/space.resolver.queries.js:34:16)\""],"timestamp":"2023-07-22T04:32:58.829Z"}
{"context":"ExceptionsHandler","label":"alkemio-server","level":"error","message":"Cannot read properties of undefined (reading 'publish')","stack":["TypeError: Cannot read properties of undefined (reading 'publish')\n    at SubscriptionPublishService.publishActivity (/usr/src/app/dist/services/subscriptions/subscription-service/subscription.publish.service.js:31:49)\n    at ActivityAdapter.memberJoined (/usr/src/app/dist/services/adapters/activity-adapter/activity.adapter.js:175:41)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async CommunityService.assignUserToRole (/usr/src/app/dist/domain/community/community/community.service.js:282:13)\n    at async ChallengeService.createChallenge (/usr/src/app/dist/domain/challenge/challenge/challenge.service.js:124:13)\n    at async SpaceService.createChallengeInSpace (/usr/src/app/dist/domain/challenge/space/space.service.js:504:30)\n    at async SpaceResolverMutations.createChallenge (/usr/src/app/dist/domain/challenge/space/space.resolver.mutations.js:116:27)"],"timestamp":"2023-07-22T10:46:57.848Z"}
{"context":"ExceptionsHandler","label":"alkemio-server","level":"error","message":"Cannot read properties of undefined (reading 'publish')","stack":["TypeError: Cannot read properties of undefined (reading 'publish')\n    at SubscriptionPublishService.publishActivity (/usr/src/app/dist/services/subscriptions/subscription-service/subscription.publish.service.js:31:49)\n    at ActivityAdapter.memberJoined (/usr/src/app/dist/services/adapters/activity-adapter/activity.adapter.js:175:41)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async CommunityService.assignUserToRole (/usr/src/app/dist/domain/community/community/community.service.js:282:13)\n    at async ChallengeService.createChallenge (/usr/src/app/dist/domain/challenge/challenge/challenge.service.js:124:13)\n    at async SpaceService.createChallengeInSpace (/usr/src/app/dist/domain/challenge/space/space.service.js:504:30)\n    at async SpaceResolverMutations.createChallenge (/usr/src/app/dist/domain/challenge/space/space.resolver.mutations.js:116:27)"],"timestamp":"2023-07-22T10:48:19.712Z"}
{"label":"alkemio-server","level":"error","message":"Authorization: unable to grant 'read' privilege: Read document: Darstellung_Plattform.png user: 8dfe23cc-2a0a-4a60-bf22-1d10b4802866","stack":["ForbiddenException: Authorization: unable to grant 'read' privilege: Read document: Darstellung_Plattform.png user: 8dfe23cc-2a0a-4a60-bf22-1d10b4802866\n    at StorageAccessController.document (/usr/src/app/dist/services/api-rest/storage-access/storage.access.controller.js:43:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"],"timestamp":"2023-07-22T11:01:12.933Z"}
{"context":"challenges","label":"alkemio-server","level":"error","message":"Unable to find Space with ID: tag","stack":["\"GraphQLError: Unable to find Space with ID: tag\\n    at new BaseException (/usr/src/app/dist/common/exceptions/base.exception.js:7:9)\\n    at new EntityNotFoundException (/usr/src/app/dist/common/exceptions/entity.not.found.exception.js:8:9)\\n    at SpaceService.getSpaceOrFail (/usr/src/app/dist/domain/challenge/space/space.service.js:356:19)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\\n    at async SpaceResolverQueries.space (/usr/src/app/dist/domain/challenge/space/space.resolver.queries.js:34:16)\""],"timestamp":"2023-07-22T11:02:58.781Z"}
{"context":"ExceptionsHandler","label":"alkemio-server","level":"error","message":"Cannot read properties of undefined (reading 'asyncIterator')","stack":["TypeError: Cannot read properties of undefined (reading 'asyncIterator')\n    at SubscriptionReadService.subscribeToRoomEvents (/usr/src/app/dist/services/subscriptions/subscription-service/subscription.read.service.js:29:44)\n    at RoomEventResolverSubscription.roomEvents (/usr/src/app/dist/domain/communication/room/room.event.resolver.subscription.js:42:41)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"],"timestamp":"2023-07-22T11:06:44.517Z"}
{"context":"ExceptionsHandler","label":"alkemio-server","level":"error","message":"Cannot read properties of undefined (reading 'asyncIterator')","stack":["TypeError: Cannot read properties of undefined (reading 'asyncIterator')\n    at SubscriptionReadService.subscribeToRoomEvents (/usr/src/app/dist/services/subscriptions/subscription-service/subscription.read.service.js:29:44)\n    at RoomEventResolverSubscription.roomEvents (/usr/src/app/dist/domain/communication/room/room.event.resolver.subscription.js:42:41)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"],"timestamp":"2023-07-22T11:06:53.258Z"}
{"context":"ExceptionsHandler","label":"alkemio-server","level":"error","message":"Cannot read properties of undefined (reading 'asyncIterator')","stack":["TypeError: Cannot read properties of undefined (reading 'asyncIterator')\n    at SubscriptionReadService.subscribeToRoomEvents (/usr/src/app/dist/services/subscriptions/subscription-service/subscription.read.service.js:29:44)\n    at RoomEventResolverSubscription.roomEvents (/usr/src/app/dist/domain/communication/room/room.event.resolver.subscription.js:42:41)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"],"timestamp":"2023-07-22T11:06:53.260Z"}
{"context":"ExceptionsHandler","label":"alkemio-server","level":"error","message":"Cannot read properties of undefined (reading 'asyncIterator')","stack":["TypeError: Cannot read properties of undefined (reading 'asyncIterator')\n    at SubscriptionReadService.subscribeToRoomEvents (/usr/src/app/dist/services/subscriptions/subscription-service/subscription.read.service.js:29:44)\n    at RoomEventResolverSubscription.roomEvents (/usr/src/app/dist/domain/communication/room/room.event.resolver.subscription.js:42:41)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"],"timestamp":"2023-07-22T11:06:53.262Z"}
{"context":"ExceptionsHandler","label":"alkemio-server","level":"error","message":"Cannot read properties of undefined (reading 'asyncIterator')","stack":["TypeError: Cannot read properties of undefined (reading 'asyncIterator')\n    at SpaceResolverSubscriptions.challengeCreated (/usr/src/app/dist/domain/challenge/space/space.resolver.subscriptions.js:45:50)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"],"timestamp":"2023-07-22T11:07:01.351Z"}
{"context":"ExceptionsHandler","label":"alkemio-server","level":"error","message":"Cannot read properties of undefined (reading 'asyncIterator')","stack":["TypeError: Cannot read properties of undefined (reading 'asyncIterator')\n    at SubscriptionReadService.subscribeToRoomEvents (/usr/src/app/dist/services/subscriptions/subscription-service/subscription.read.service.js:29:44)\n    at RoomEventResolverSubscription.roomEvents (/usr/src/app/dist/domain/communication/room/room.event.resolver.subscription.js:42:41)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"],"timestamp":"2023-07-22T11:08:10.160Z"}
{"context":"ExceptionsHandler","label":"alkemio-server","level":"error","message":"Cannot read properties of undefined (reading 'asyncIterator')","stack":["TypeError: Cannot read properties of undefined (reading 'asyncIterator')\n    at SubscriptionReadService.subscribeToActivities (/usr/src/app/dist/services/subscriptions/subscription-service/subscription.read.service.js:26:49)\n    at ActivityLogResolverSubscriptions.activityCreated (/usr/src/app/dist/services/api/activity-log/activity.log.resolver.subscriptions.js:45:45)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"],"timestamp":"2023-07-22T11:08:10.376Z"}
{"context":"ExceptionsHandler","label":"alkemio-server","level":"error","message":"Cannot read properties of undefined (reading 'asyncIterator')","stack":["TypeError: Cannot read properties of undefined (reading 'asyncIterator')\n    at SubscriptionReadService.subscribeToRoomEvents (/usr/src/app/dist/services/subscriptions/subscription-service/subscription.read.service.js:29:44)\n    at RoomEventResolverSubscription.roomEvents (/usr/src/app/dist/domain/communication/room/room.event.resolver.subscription.js:42:41)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"],"timestamp":"2023-07-22T11:08:39.754Z"}
{"context":"ExceptionsHandler","label":"alkemio-server","level":"error","message":"Cannot read properties of undefined (reading 'asyncIterator')","stack":["TypeError: Cannot read properties of undefined (reading 'asyncIterator')\n    at SubscriptionReadService.subscribeToRoomEvents (/usr/src/app/dist/services/subscriptions/subscription-service/subscription.read.service.js:29:44)\n    at RoomEventResolverSubscription.roomEvents (/usr/src/app/dist/domain/communication/room/room.event.resolver.subscription.js:42:41)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"],"timestamp":"2023-07-22T11:08:39.756Z"}
{"context":"ExceptionsHandler","label":"alkemio-server","level":"error","message":"Cannot read properties of undefined (reading 'asyncIterator')","stack":["TypeError: Cannot read properties of undefined (reading 'asyncIterator')\n    at SubscriptionReadService.subscribeToRoomEvents (/usr/src/app/dist/services/subscriptions/subscription-service/subscription.read.service.js:29:44)\n    at RoomEventResolverSubscription.roomEvents (/usr/src/app/dist/domain/communication/room/room.event.resolver.subscription.js:42:41)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"],"timestamp":"2023-07-22T11:08:39.758Z"}
{"context":"ExceptionsHandler","label":"alkemio-server","level":"error","message":"Cannot read properties of undefined (reading 'asyncIterator')","stack":["TypeError: Cannot read properties of undefined (reading 'asyncIterator')\n    at CalloutResolverSubscriptions.calloutPostCreated (/usr/src/app/dist/domain/collaboration/callout/callout.resolver.subscriptions.js:50:45)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"],"timestamp":"2023-07-22T11:09:14.380Z"}
/usr/src/app/dist/services/subscriptions/subscription-service/subscription.publish.service.js:31
        return this.activityCreatedSubscription.publish(subscription_type_1.SubscriptionType.ACTIVITY_CREATED, payload);
                                                ^

TypeError: Cannot read properties of undefined (reading 'publish')
    at SubscriptionPublishService.publishActivity (/usr/src/app/dist/services/subscriptions/subscription-service/subscription.publish.service.js:31:49)
    at ActivityAdapter.whiteboardCreated (/usr/src/app/dist/services/adapters/activity-adapter/activity.adapter.js:142:41)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections
