### ISSUE TITLE
BUG: Callout create flow crashes when adding reference

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6043]
**Describe the bug**
When creating a callout, everything goes fine until I click + References -> this closes the dialog!
In the edit flow, I can add references

https://sandbox-alkem.io/alkemio/knowledge-base

**To Reproduce**

- add screenshots 
- add url on the location with problem
An error is logged to the browser console:
Uncaught Error: No StorageConfigContext provided.
Uncaught Error: No StorageConfigContext provided.
at useStorageConfigContext (StorageConfigContext.tsx:15:11)
at FormikFileInput (FormikFileInput.tsx:25:25)

**Expected behavior**

**Screenshots**

![Image](https://github.com/alkem-io/client-web/assets/38861315/5103c9e3-64bf-485f-8e4e-d977868586f4)

When I click on References:

![Image](https://github.com/alkem-io/client-web/assets/38861315/cccafbc9-b72d-459e-b498-9ae6f433f937)

**Comment by Comoque1** [comment]
Tested OK on all callout types on Subspace type challenge and opportunity.
